### ISSUE TITLE
labcol2 causes incorrect @span in erepeat

### ISSUE THREAD

**Issue by NilsEnevoldsen** [benjann/estout#12]
Input:
```stata
sysuse auto
eststo: quietly reg price weight
estout using "example.tex", style(tex) replace drop(_cons) ///
  mgroups("mgroup", span erepeat(\cmidrule(lr){@span})) ///
  mlabels("mlabel", span erepeat(\cmidrule(lr){@span})) ///
  collabels("collabel", span erepeat(\cmidrule(lr){@span})) ///
  labcol("Qux", title("Foo" "Bar" "Baz"))
eststo clear
```

Expected:
```stata
            &    Foo     &mgroup      \\\cmidrule(lr){3-3}
            &    Bar     &mlabel      \\\cmidrule(lr){3-3}
            &    Baz     &collabel    \\\cmidrule(lr){3-3}
weight      &    Qux     &    2.044063\\
```

Actual:
```stata
            &    Foo     &mgroup      \\\cmidrule(lr){2-2}
            &    Bar     &mlabel      \\\cmidrule(lr){2-2}
            &    Baz     &collabel    \\\cmidrule(lr){2-2}
weight      &    Qux     &    2.044063\\
```

When compiled with…
```latex
\documentclass{article}
\usepackage{booktabs}
\begin{document}
\begin{tabular}{lcc}
\input{example}
\end{tabular}
\end{document}
```

…the expected result is…
<img width="299" alt="screen shot 2016-07-10 at 12 42 17 pm" src="https://cloud.githubusercontent.com/assets/222743/16714783/d5a5680c-469b-11e6-8541-833a893e7504.png">

…and the actual result is:
<img width="307" alt="screen shot 2016-07-10 at 12 40 41 pm" src="https://cloud.githubusercontent.com/assets/222743/16714773/a49cb3dc-469b-11e6-8b72-8b63c06c1a78.png">

Originally reported as [“Issue with -@span- in -estout-” by Albert Sfredo, Statalist](http://www.statalist.org/forums/forum/general-stata-discussion/general/1348715-issue-with-span-in-estout)

**Comment by benjann** [comment]
Yes, bug. `@span` does not take into account the extra column created by `labcol()`. I'll try to post a fix.

**Comment by benjann** [comment]
This should now be fixed.
