### ISSUE TITLE
-estout matrix()- not working in combination with option style()

### ISSUE THREAD

**Issue by dirtyhawk** [benjann/estout#16]
Hi,

I stumbled upon an issue in estout that evolves in a scenario that, probably, is quite seldomly used:
When estout is invoked to work on a matrix (_estout matrix(X)_), adding the option _style()_ to the estout call makes it abort with the error message 198 (invalid syntax), even if the specified style file contains the exact same options than a manuall call to estout.

I tried to illustrate this in a minimal example:

```Stata
clear
capture : program drop estout

* create a simple matrix
matrix A = (1,2\2,1)

* create a minimal estout defaults definition file
file open deffile using "estout_matrixtest.def" , write text replace
file write deffile `"* estout_matrixtest.def: estout defaults file for -estout-"' _newline
file write deffile `"title This is my title"' _newline // <-- this is the title; all other options are copied from estout's defaults
file write deffile `"varwidth 13"' _newline
file write deffile `"modelwidth 12"' _newline
file write deffile `"abbrev abbrev"' _newline
file write deffile `"smcltags smcltags"' _newline
file write deffile `"smclrules smclrules"' _newline
file write deffile `"interaction `"" # ""'"' _newline
file close deffile

* estout the minimal matrix, with manual title option
estout matrix(A) , title("This is my title") 	// <-- this works

* estout the minimal matrix, with defaults file title option
estout matrix(A) , style(matrixtest)		// <-- this, unexpectedly, does not
exit 0
// EOF
```
It seems that, internally, some return values of the sub-program MatrixMode are overwritten before saved to local macros, so that at a later point the information is missing. I already tried to implement a fix for this, which might not solve the issue in the most elegant way possible, but works in my test scenario. As soon as I understood how to fork the repository, commit my change, and create a pull request from it, I will do so.

Regards
Bela

**Comment by benjann** [comment]
I now looked into this. The reason was indeed that when reading from a defaults file the returns from subprogram `MatrixMode` were cleared before being processed (due to `findfile` and `file read` returning results in `r()`). Your proposed solution is perfect. The fixed code will be in the next SSC update.
