### ISSUE TITLE
Keep keeps too many variables

### ISSUE THREAD

**Issue by matthieugomez** [benjann/estout#23]
I think there is a bug in estout for Stata 16: `keep(x)` keeps all variables with the prefix `x`
```
set obs 100
gen y = _n
gen x = _n
gen x_1 = _n
gen z = _n
reg y x x_1 z
estimates store m
estout m, keep(x)
-------------------------
                        m
                        b
-------------------------
x                       1
x_1                     0
-------------------------
```

**Comment by benjann** [comment]
This is an issue that was introduced in Stata 16. Meanwhile, Stata 16 has been fixed. That is, if you update Stata (type -update all- and follow the instructions), the problem should go away.

For background information see [here](https://www.statalist.org/forums/forum/general-stata-discussion/general/1513398-esttab-indicator-order-creating-a-coefficient-not-found-error-r-111).

**Comment by matthieugomez** [comment]
Awesome! Thanks for the speedy answer.
