### ISSUE TITLE
Option for float placement in esttab

### ISSUE THREAD

**Issue by JKRhb** [benjann/estout#26]
I really enjoy using `esttab `for creating LaTeX tables out of Stata. However, it would be nice to be able to define the placement of a table from within the command using a designated option. So far it seems as if `htbp` is hardcoded into the command:

https://github.com/benjann/estout/blob/d392e710c999be478c208c8e3cc8fd4f86bb6ccb/esttab.ado#L206

Could you add this as a feature?

**Comment by benjann** [comment]
Yes, this is hardcoded. Personally I typically find it more convenient to use esttab/estout only to generate the table contents (i.e. not use the -float- option) and put the rest together directly in LaTeX. If you need to automate this, then maybe use the -file- command to write corresponding lines to the LaTeX file before/after the table contents.

**Comment by benjann** [comment]
That is, I do not have plans to make the -float- option more powerful.

**Comment by JKRhb** [comment]
Thank you for your response! I agree, the way it is implemented right now is actually flexible enough and I got it to work the way I wanted it. Thank you, however, for taking my feature request into consideration :)
