### ISSUE TITLE
estout: minor issue with formatting of confidence intervals

### ISSUE THREAD

**Issue by MarcGillaizeau** [benjann/estout#29]
Dear Mr. Jann,

First of all thank you very much for the estout command, it is a godsend.
I came across a small issue for formatting the confidence intervals.
Basically, when custom number formats are specified, only the last one prevails.
For instance, if I have 3 coefficients and type:

`estout, cells(ci(fmt(1 1 2)))` 

All CIs will show 2 decimals.

I identified the issue in the ADO file, and fixed it as best I could.
On row 1,513 the current code is:

``local format: word `r' of `ci_fmt'``

I changed it into:

```local format: word `r' of ``vi'_fmt'```

I think the fix is correct. At least it solved my issue and the CIs now show the desired number of decimals.
But the code is a bit overwhelming so I hope it doesn't mess with the rest of the code.

Very best,

Marc

**Comment by benjann** [comment]
Thanks for reporting this and suggesting an appropriate fix. The latest update now works with correctly with multiple formats in `cells(ci(fmt()))`.
ben
