### ISSUE TITLE
Is that possible to set a gap between tables?

### ISSUE THREAD

**Issue by fredericky123** [benjann/estout#38]
Right now, different tables only have one line space, difficult to locate each table.
Can we set a second table begins from next page in Word? Thanks a ton!

**Comment by benjann** [comment]
Hi, to add page breaks between tables you could include RFT command `\pagebb` in the `title()` option. Example:

```Stata
sysuse auto
reg price weight foreign
esttab . using ~/mytable.rtf, title(Table 1) replace
esttab . using ~/mytable.rtf, title(\pagebb Table 2) append
esttab . using ~/mytable.rtf, title(\pagebb Table 3) append
```

ben

**Comment by fredericky123** [comment]
Thanks Ben!
