### ISSUE TITLE
can we add an option to exchange the orders of variables in an interaction?

### ISSUE THREAD

**Issue by fredericky123** [benjann/estout#40]
For your reference:
https://www.statalist.org/forums/forum/general-stata-discussion/general/1658998-how-to-change-the-order-of-variables-in-interaction-for-esttab

**Comment by benjann** [comment]
Sorry, I have no plans to add such an option. Use option `coeflab()` as suggested by Andrew.

**Comment by fredericky123** [comment]
I see, thanks!
