### ISSUE TITLE
Is that possible to supress the last second line?

### ISSUE THREAD

**Issue by fredericky123** [benjann/estout#41]
![image](https://user-images.githubusercontent.com/13982749/163089260-cfb12f28-ba86-45cc-99e5-9ae7d358a5df.png)
Can we supress the last second line?
Can we set font size of the first and last line to be 1.5pt or 3pt? Some papers require that the first and last line to be thicker than the middle line.
Best,
Thank you!

**Comment by benjann** [comment]
For screen display in Stata you could get rid of the rule before the footer as follows:
```Stata
clear all
sysuse auto, clear
regress price foreign
esttab, nogap prefoot("{...}")

----------------------------
                      (1)   
                    price   
----------------------------
foreign             312.3   
                   (0.41)   
_cons              6072.4***
                  (14.76)   
N                      74   
----------------------------
t statistics in parentheses
* p<0.05, ** p<0.01, *** p<0.001
```
In RTF output, this is not possibly I am afraid. There are also no options to determine the rendering of the lines. You'd have to do such formatting manually in Word or so after generating the table. `esttab` only has very limited support for RTF. If basically just exports a plain table; specific formatting has to be done elsewhere. In LaTeX there are more possibilities (see, e.g., [http://repec.sowi.unibe.ch/stata/estout/latex.html](http://repec.sowi.unibe.ch/stata/estout/latex.html))
ben

**Comment by fredericky123** [comment]
I see, Thank you!
