### ISSUE TITLE
how to output the results after "pstest"

### ISSUE THREAD

**Issue by fredericky123** [benjann/estout#52]
I want to output the table results of "pstest" to rtf file, how can I ?
Thanks a ton!
```
sysuse auto, clear
psmatch2 foreign mpg rep78
pstest mpg rep78
```
<img width="613" alt="image" src="https://user-images.githubusercontent.com/13982749/204799988-efed90c7-af13-48de-9cb7-43e2cf41b915.png">

**Comment by benjann** [comment]
It does not seem to me that `pstest` stores these results anywhere, which makes it difficult to export them.

**Comment by fredericky123** [comment]
I see. Thank you.
