### ISSUE TITLE
how to use rename option for factor variables?

### ISSUE THREAD

**Issue by fredericky123** [benjann/estout#55]
No matter what I set, the factor variable is not be wrapped to one row
```
sysuse auto,clear
gen foreign1=foreign+1
eststo clear
eststo:reg price mpg i.foreign
eststo:reg price mpg i.foreign1
esttab, rename(foreign foreign1) label nobaselevels
esttab, rename(foreign foreign1) nobaselevels
```

**Comment by fredericky123** [comment]
Thanks a ton! If I still have a _3.foreign2_ need to be wrapped, how to set it?

**Comment by NilsEnevoldsen** [comment]
Did you check out http://repec.sowi.unibe.ch/stata/estout/help-estout.html#stlog-1-rename? You'd do

```stata
rename(1.foreign 2.foreign1 1.foreign 3.foreign2)
```

If you have several models, none of which has the obviously correct coefficient names, then it may be most readable or intuitive to invent an entirely new coefficient name and rename everything to that, e.g.

```stata
rename(foo 1.foreign foo 2.foreign1 foo 3.foreign2)
```

**Comment by fredericky123** [comment]
I see, thanks! Sorry not to understand the manaual correctly.
