### ISSUE TITLE
Can we leave blanks for coefficients of omitted variables?

### ISSUE THREAD

**Issue by fredericky123** [benjann/estout#56]
```
sysuse auto,clear
eststo clear
eststo: reg price mpg rep78 foreign weight if foreign ==1
esttab
```
<img width="275" alt="image" src="https://user-images.githubusercontent.com/13982749/216757005-0e5b5df4-1353-4649-b64c-c41721c17540.png">

**Comment by fredericky123** [comment]
My specific situation is more like this: I want to keep "foreign" above the interaction.
```
eststo clear
sysuse auto,clear
eststo: reg price mpg rep78 foreign c.weight##c.gear_ratio if foreign ==1
eststo: reg price mpg rep78 foreign c.weight##c.gear_ratio if rep78 ==3
esttab,noomitted
esttab
```
<img width="376" alt="image" src="https://user-images.githubusercontent.com/13982749/216876011-03b8c748-b041-4b90-9ab4-afead35214e4.png">
<img width="366" alt="image" src="https://user-images.githubusercontent.com/13982749/216876060-dec96666-1ffc-47ca-8cdc-d0f58ecb7126.png">

**Comment by fredericky123** [comment]
Thanks for the reply! I have about 20 variables, therefore using `order' makes the code to be redundant. I am wondering whether there is more simple way.

**Comment by dreistein543** [comment]
a ` local` or ` global ` can simplify your code. BTW, you don’t need to list all of your variables in ` order()`

**Comment by fredericky123** [comment]
Thanks!

**Comment by NilsEnevoldsen** [comment]
It isn't applicable to every situation, but you can also use wildcards in `order()`. For example, I have used `order(*#* *)`.

**Comment by NilsEnevoldsen** [comment]
I think wildcards are matched left-to-right, so the first `*` captures everything and the rest of the tokens match nothing. Sorry. Like I said, it doesn't work for every situation.

**Comment by fredericky123** [comment]
I see, thanks all the same.

**Comment by fredericky123** [comment]
@NilsEnevoldsen Can we use the option of "substitute" to realize this?

eststo clear
sysuse auto,clear
eststo: reg price mpg rep78 foreign c.weight##c.gear_ratio if foreign ==1
eststo: reg price mpg rep78 foreign c.weight##c.gear_ratio if rep78 ==3
esttab,omitted substitute("0.0" "  ")

**Comment by fredericky123** [comment]
`esttab,omitted b(3) substitute("0.000" " ")`
can replace the 0.000 to blank, how to replace the misssing values of t statistics for foreign and rep78 in the example mentioned above?

**Comment by benjann** [comment]
Like this? 

```
eststo clear
sysuse auto,clear
eststo: reg price mpg rep78 foreign c.weight##c.gear_ratio if foreign ==1
eststo: reg price mpg rep78 foreign c.weight##c.gear_ratio if rep78 ==3
esttab, omitted substitute(" 0 " "   " "{txt:(}.{txt:)}" "   ")
```

The details depend on output format. In the example, output format is SMCL, in which case t-values are types as `{txt:(}#{txt:)}`, where `#` is the value of the t-value.

**Comment by benjann** [comment]
Try the following:

```
eststo clear
sysuse auto,clear
eststo: reg price mpg rep78 foreign c.weight##c.gear_ratio if foreign ==1
eststo: reg price mpg rep78 foreign c.weight##c.gear_ratio if rep78 ==3
esttab using table.rtf, omitted substitute("{0}" "{}" "{(.)}" "{}")
```

**Comment by fredericky123** [comment]
Great, this is exactly what I want! Thanks a ton!
