### ISSUE TITLE
How to match coefficients across models for single term and interaction term

### ISSUE THREAD

**Issue by fredericky123** [benjann/estout#62]
```
sysuse auto,clear
set seed 123
generate altmpg = invnorm(uniform())
eststo clear
eststo: quietly regress price c.weight##c.mpg
eststo: quietly regress price c.weight##c.altmpg
esttab
esttab, rename(altmpg "Mpg" mpg "Mpg")
```
<img width="424" alt="image" src="https://github.com/benjann/estout/assets/13982749/2c92a70d-9364-4320-96c3-8a4ad7611ffe">

In the example, the interaction term did't be matched,  how to set all coefficients of "mpg" and "altmpg" be matched? If I have ten models, I want the alternative "mpg" (inbckuding its interction terms) to be output in the same cell, how to set this?
In other way, can we rename a list of varlables in a batch so that the list of varables will be renamed (including the single term and interaction term)

**Comment by benjann** [comment]
Option `rename()` operates at the level of individual coefficients, not variables. You need to rename each coefficient individually. In your case you could type
```
esttab, rename(altmpg mpg c.weight#c.altmpg c.weight#c.mpg)
```
ben

**Comment by fredericky123** [comment]
Thanks Ben!
Is that possible to use the option "varlabels" to rename each variables and stack the variables with the same label to one cell?

**Comment by benjann** [comment]
Nope. `varlabels()` only assigns labels, it does not affect how results will be arranged.

**Comment by fredericky123** [comment]
I see. I have a list of variables to be renamed when output about 10 models into a table. Look forward an option that can make "rename" more efficiently.
Thanks!
