### ISSUE TITLE
Suggestion: throw a notification or warning when the user tabulates stored estimations (by default) without active estimations

### ISSUE THREAD

**Issue by NilsEnevoldsen** [benjann/estout#9]
In regards to Issue #8, I've been thinking about how to prevent this confusion. I suggest throwing a notification or warning when

1. *namelist* is empty,
2. there are stored estimation results,
3. there are active estimation results, *and*
4. the active estimation results are not present in the stored estimation results. I think this can be determined with `e(_estimates_name)` and `$eststo`.

The situation is
```stata
eststo: reg price weight
reg price length
esttab
```

The notification would be something like

> You have not specified a list of estimation results to tabulate. There are both stored estimation results and unstored estimation results. The list of estimation results to tabulate will default to _all, which is the list of all stored estimation results. Specify . to tabulate active estimation results.

**Comment by benjann** [comment]
The newest update of estout, which should be available from SSC in some days, now displays a (brief) note in this case. (I will also update estout on github, but I'm out of battery and have to do this later.)
